name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - uses: extractions/setup-just@v3.1.0
        with:
          just-version: "1.46.0"

      - uses: bufbuild/buf-setup-action@v1.50.0

      - name: Generate
        run: just proto && just templ

      - name: Lint
        run: just lint && just proto-lint

      - name: Test with coverage
        run: just coverage

      - uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.filtered.out
